steps:
  # Build the container image using our Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/papillon-backend', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/papillon-backend']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'papillon-backend'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/papillon-backend'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'NODE_ENV=production,GOOGLE_CLOUD_API_KEY=AIzaSyBiqxFAooCoJX1y-_IgDbVAtoaZ2SVKmxk,GEMINI_MODEL=gemini-2.0-flash-exp,FIREBASE_PROJECT_ID=gen-lang-client-0930707875,ELEVENLABS_API_KEY=sk_51c6df326ba2847994ab912eb3a34fefacd286f202c55948,GOOGLE_APPLICATION_CREDENTIALS_JSON=${_FIREBASE_SECRET}'
    - '--set-secrets'
    - 'GOOGLE_APPLICATION_CREDENTIALS_JSON=firebase:latest'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/papillon-backend'

substitutions:
  _GOOGLE_CLOUD_API_KEY: 'AIzaSyBiqxFAooCoJX1y-_IgDbVAtoaZ2SVKmxk'
  _FIREBASE_PROJECT_ID: 'gen-lang-client-0930707875'
  _GEMINI_MODEL: 'gemini-2.0-flash-exp'

options:
  logging: CLOUD_LOGGING_ONLY 